### ISSUE TITLE
Plugin doesn't load on Spigot for 1.8.6

### ISSUE THREAD

**Issue by Vellric** [jaboatman/SecretDoors#1]
Hello. I would like to use SecretDoors, a really nice plugin I have use in the past. But it doesn't load. I hope that you are still active. Here the pastebin of the log/error:
http://pastebin.com/uBWXusZH

**Comment by jaboatman** [comment]
You need Java 8.

**Comment by Vellric** [comment]
Thanks man! Never think about checking that.
